version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: maintenance_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maintenance_app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projet_maintenance_pma
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: user 
      PMA_PASSWORD: user 
    ports:
      - "8080:80"

volumes:
  db_data:
